version: '3'
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "8080:8080"
    environment:
      - DISPLAY=:99
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
  dns:
    build:
      context: .
      dockerfile: Dockerfile.dns
    ports:
      - "5354:53/udp"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
